### ISSUE TITLE
Using minion reads with LAST

### ISSUE THREAD

**Issue by lfaller** [mcfrith/last-rna#1]
Hello all,

I am interested in comparing two canu assemblies using LAST. The *reference* assembly has 25 contigs and the *query* assembly has 21 contigs. The assemblies are for GC rich bacteria (same species but different strains, so I expect them to be somewhat similar). 

I followed the instructions provided here: https://github.com/mcfrith/last-rna/blob/master/last-long-reads.md

However, the output I get seems to just be the comments:

```
# make an index using the WT strain
~/bin/lastdb -P40 -uNEAR -R01 WT_db reference.contigs.fasta

# align mutant against the WT strain
~/bin/lastal -P40 WT_db query.contigs.fasta
# LAST version 885
#
# a=21 b=9 A=21 B=9 e=60 d=0 x=59 y=44 z=59 D=1e+06 E=5e+11
# R=01 u=0 s=2 S=0 M=0 T=0 m=10 l=1 n=10 k=1 w=1000 t=4.36661 j=3 Q=0
# WT_db
# Reference sequences=25 normal letters=0
# lambda=0.228526 K=0.433378
#
#    A  C  G  T
# A  6 -18 -18 -18
# C -18  6 -18 -18
# G -18 -18  6 -18
# T -18 -18 -18  6
#
# Coordinates are 0-based.  For - strand matches, coordinates
# in the reverse complement of the 2nd sequence are used.
#
# name start alnSize strand seqSize alignment
#
# batch 0
# Query sequences=21
```

I also tried submitting these two assemblies to the web service but received the message "no alignments were found":

![screen shot 2017-10-16 at 3 32 06 pm](https://user-images.githubusercontent.com/7854149/31631273-3d84ede6-b287-11e7-83c8-8988dfbf9865.png)

I am new to LAST. Could it be that my sequences are too similar? Is this an appropriate problem for LAST?

Thanks for any advice!
~Lina

**Comment by mcfrith** [comment]
Hi Lina,

I'm afraid this reply is both late and useless.

I think it's an appropriate problem, and "too similar" should not matter. I'm surprised you're getting no alignments. The only way to figure this out is if you can share your sequences.

(I would recommend also using last-split, and probably last-train. But "no alignments" suggests some deeper problem.)

Have a nice day,
Martin

**Comment by lfaller** [comment]
Thank you for the quick reply! If you don't mind taking a look at my sequences, I will send them to you via email.

Best,
~Lina
